version: '3.8'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "8080:80"
    depends_on:
      - json-server

  json-server:
    build:
      context: .
      dockerfile: Dockerfile.jsonserver
    ports:
      - "3000:3000"
